"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BadgeCheck, Check, ChevronRight, CircleDot, Droplets, Factory, FlaskConical, Gauge, Leaf, Menu, MessageCircle, Play, ShieldCheck, Sparkles, Sprout, Wind, X, Zap } from "lucide-react";
import { CookieConsent } from "@/components/cookie-consent";

const navigation = [["Susttenta", "#susttenta"], ["Embiofert", "#embiofert"], ["Embio", "#linha-embio"], ["TLC Agro", "#tlc-agro"], ["Resultados", "#resultados"]];
const problems = [
  { icon: Wind, title: "Gases e odores", text: "Manejo biológico para ambientes e sistemas de dejetos." },
  { icon: Droplets, title: "Lagoas e sedimentos", text: "Aeração, homogeneização e apoio à degradação orgânica." },
  { icon: CircleDot, title: "Larvas e moscas", text: "Soluções específicas para instalações e áreas externas." },
  { icon: Zap, title: "Biodigestores", text: "Ambiência sem comprometer a matéria orgânica destinada ao biogás." },
  { icon: Factory, title: "Efluentes complexos", text: "Alternativas para operações rurais, industriais e agroindustriais." },
];
const embiofertBenefits = ["Aeração com microbolhas", "Homogeneização dos dejetos", "Apoio à degradação orgânica", "Redução de odores e agentes nocivos", "Menor acúmulo de sedimentos", "Projeto conforme a lagoa"];
const faqs = [
  ["A Susttenta vende produtos Embio e TLC Agro?", "A Susttenta representa as duas linhas e orienta a escolha conforme o problema da propriedade. O atendimento começa pelo diagnóstico da aplicação."],
  ["Qual é a diferença entre Embio 3100 e Embio 6000?", "O Embio 3100 é voltado à ambiência interna de granjas suínas que não destinam o dejeto diretamente ao biodigestor. O Embio 6000 foi desenvolvido para granjas que enviam dejetos à produção de biogás."],
  ["O que compõe o Tratamento Embiofert?", "A solução integra o bioestimulador Embio 3000 e o Propulsor Embio para favorecer a aeração, a homogeneização e a degradação da matéria orgânica em lagoas de dejetos."],
  ["Como funciona o Ecomax?", "O atrativo orgânico é colocado na armadilha, que deve ser posicionada em área estratégica. As moscas são atraídas e ficam retidas no reservatório, que precisa ser esvaziado periodicamente."],
  ["O Ecomax pode ser instalado em qualquer lugar?", "A indicação oficial prioriza áreas externas ou bem ventiladas, em pontos com incidência de moscas e fora do alcance de crianças e animais. A equipe orienta a distribuição adequada."],
  ["Vocês acompanham a aplicação?", "Sim. A proposta da Susttenta é oferecer atendimento consultivo, orientar a escolha e acompanhar a aplicação de acordo com o sistema existente."],
];

function ContactLink({ children, className = "", ariaLabel }: { children: React.ReactNode; className?: string; ariaLabel?: string }) {
  return <a href="#contato" className={className} aria-label={ariaLabel}>{children}</a>;
}

export function SiteClient() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 28);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    const elements = document.querySelectorAll<HTMLElement>("[data-reveal]");
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("is-visible")), { threshold: 0.12, rootMargin: "0px 0px -8%" });
    elements.forEach((element) => observer.observe(element));
    return () => { window.removeEventListener("scroll", onScroll); observer.disconnect(); };
  }, []);

  return <>
    <div className="top-note"><span>Biotecnologia aplicada ao campo</span><span>Representante Embio + TLC Agro</span></div>
    <header className={`site-header ${scrolled ? "site-header--scrolled" : ""}`}>
      <div className="site-header__inner">
        <a className="brand" href="#inicio" aria-label="Susttenta — início"><Image unoptimized className="brand__symbol" src="/favicon-master-1024.png" alt="" width={52} height={52} priority /><Image unoptimized className="brand__wordmark" src="/logo-susttenta-wordmark.png" alt="Susttenta" width={154} height={24} priority /></a>
        <nav className="desktop-nav" aria-label="Navegação principal">{navigation.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav>
        <ContactLink className="header-cta"><MessageCircle size={17} /> Falar com a Susttenta</ContactLink>
        <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <nav className="mobile-nav" aria-label="Navegação móvel">{navigation.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}<a href="#contato" onClick={() => setMenuOpen(false)}>Solicitar orientação</a></nav>}
    </header>

    <main>
      <section id="inicio" className="hero">
        <div className="hero__mesh" />
        <div className="container hero__grid">
          <div className="hero__copy" data-reveal><div className="eyebrow"><span /> Tecnologia que trabalha com a natureza</div><h1>Soluções <em>biotecnológicas</em> para o campo produzir melhor.</h1><p className="hero__lead">Granjas, propriedades rurais, lagoas, biodigestores e controle de moscas com diagnóstico, tecnologia e acompanhamento.</p><div className="hero__actions"><ContactLink className="primary-button"><MessageCircle size={19} /> Falar com um especialista <ArrowRight size={18} /></ContactLink><a className="secondary-button" href="#solucoes">Conhecer soluções <ChevronRight size={17} /></a></div><div className="hero__brands"><span>Susttenta representa</span><strong>EMBIO</strong><i /><strong>TLC AGRO</strong></div></div>
          <div className="hero__visual" data-reveal><div className="hero__photo"><Image unoptimized src="/media/tlc/ecomax-hero-bg.png" alt="Animais em propriedade rural" fill priority sizes="(max-width: 900px) 100vw, 48vw" /></div><div className="hero__orbit hero__orbit--one" /><div className="hero__orbit hero__orbit--two" /><div className="hero__metric hero__metric--top"><Leaf size={18} /><div><strong>2 linhas</strong><span>uma orientação</span></div></div><div className="hero__metric hero__metric--bottom"><Sparkles size={18} /><div><strong>Campo real</strong><span>solução específica</span></div></div></div>
        </div>
        <div className="hero__ticker"><div>BIOTECNOLOGIA <i /> AMBIÊNCIA <i /> DEJETOS <i /> BIODIGESTORES <i /> CONTROLE DE MOSCAS <i /> ATENDIMENTO CONSULTIVO <i /></div></div>
      </section>

      <section id="susttenta" className="section brand-platform"><div className="container">
        <header className="platform-intro" data-reveal><div><div className="eyebrow"><span /> Uma empresa, duas frentes estratégicas</div><h2>A Susttenta conecta cada problema à tecnologia certa.</h2></div><p>Não somos uma página de um único produto. Somos o ponto de orientação entre a realidade da sua operação e soluções especializadas para tratamento biológico e controle de moscas.</p></header>
        <div className="brand-cards"><article className="brand-card brand-card--embio" data-reveal><span className="brand-card__number">01</span><div className="brand-card__icon"><FlaskConical /></div><small>BIOTECNOLOGIA AMBIENTAL</small><h3>Embio</h3><p>Bioestimuladores e equipamentos para granjas, lagoas, dejetos, biodigestores e efluentes.</p><a href="#embiofert">Explorar linha Embio <ArrowRight size={17} /></a></article><article className="brand-card brand-card--tlc" data-reveal><span className="brand-card__number">02</span><div className="brand-card__icon"><CircleDot /></div><small>CONTROLE DE MOSCAS</small><h3>TLC Agro</h3><p>Ecomax, atrativo orgânico e armadilhas para manejo de moscas em áreas rurais e externas.</p><a href="#tlc-agro">Conhecer Ecomax <ArrowRight size={17} /></a></article></div>
      </div></section>

      <section id="solucoes" className="problems-section"><div className="container"><header className="section-heading" data-reveal><div className="eyebrow"><span /> Começamos pelo problema</div><h2>O que precisa mudar na sua operação?</h2><p>O cenário define a solução. A Susttenta ajuda a identificar o ponto crítico antes de indicar um produto.</p></header><div className="problem-grid">{problems.map(({ icon: Icon, title, text }, index) => <article key={title} data-reveal><span className="problem-index">0{index + 1}</span><Icon size={25} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section id="embiofert" className="embiofert-section"><div className="embiofert__glow" /><div className="container embiofert-grid"><div className="embiofert-copy" data-reveal><span className="solution-kicker">SOLUÇÃO PRINCIPAL · EMBIO</span><h2>Tratamento <em>Embiofert</em></h2><h3>Embio 3000 + Propulsor Embio</h3><p>Uma solução integrada para compostagem líquida, ideal para dejetos bovinos e suínos. O bioestimulador atua em conjunto com a aeração e a movimentação promovidas pelo Propulsor.</p><div className="embiofert-formula"><span><FlaskConical /> Bioestimulação</span><b>+</b><span><Gauge /> Aeração e fluxo</span><b>=</b><span><Sprout /> Manejo eficiente</span></div><ContactLink className="primary-button primary-button--yellow">Quero avaliar minha lagoa <ArrowRight size={18} /></ContactLink></div><div className="embiofert-product" data-reveal><div className="product-halo" /><Image unoptimized src="/media/embio-official/embiofert.webp" alt="Embio 3000 e Propulsor Embio" width={900} height={900} sizes="(max-width: 900px) 90vw, 44vw" /><span className="official-media"><BadgeCheck size={15} /> Imagem oficial Embio</span></div></div><div className="container embiofert-benefits">{embiofertBenefits.map((benefit) => <span key={benefit}><Check size={15} /> {benefit}</span>)}</div></section>

      <section id="linha-embio" className="section selection-section"><div className="container"><header className="section-heading section-heading--center" data-reveal><div className="eyebrow"><span /> Escolha conforme o destino do dejeto</div><h2>3100 ou 6000? O sistema da granja decide.</h2><p>Os dois atuam na ambiência interna, mas foram desenvolvidos para cenários diferentes.</p></header><div className="selection-grid">
        <article className="selection-card" data-reveal><div className="selection-card__media"><span>SEM DESTINO DIRETO AO BIODIGESTOR</span><Image unoptimized src="/media/embio-official/embio-3100.webp" alt="Produto Embio 3100" width={900} height={900} /></div><div className="selection-card__copy"><small>AMBIÊNCIA EM GRANJAS SUÍNAS</small><h3>Embio 3100</h3><p>Para controle de gases, odores, larvas e moscas no ambiente interno, com apoio à redução do cascão e à rotina de limpeza.</p><div className="attention-note"><ShieldCheck size={18} /><span><strong>Atenção à indicação:</strong> não deve ser usado quando o dejeto tem como destinação final o biodigestor.</span></div><ContactLink className="text-button">Consultar Embio 3100 <ArrowRight size={17} /></ContactLink></div></article>
        <article className="selection-card selection-card--blue" data-reveal><div className="selection-card__media"><span>GRANJAS COM BIODIGESTOR</span><Image unoptimized src="/media/embio-official/embio-6000.webp" alt="Produto Embio 6000" width={948} height={1660} /></div><div className="selection-card__copy"><small>AMBIÊNCIA + PRESERVAÇÃO ORGÂNICA</small><h3>Embio 6000</h3><p>Desenvolvido para instalações que enviam os dejetos à produção de biogás. Atua em gases, odores, larvas e moscas sem comprometer o material destinado ao biodigestor.</p><div className="attention-note"><Zap size={18} /><span><strong>Compatível com o processo:</strong> preserva a matéria orgânica para posterior geração de biogás.</span></div><ContactLink className="text-button">Consultar Embio 6000 <ArrowRight size={17} /></ContactLink></div></article>
      </div></div></section>

      <section id="tlc-agro" className="tlc-section"><div className="tlc-noise" /><div className="container tlc-grid"><div className="tlc-copy" data-reveal><span className="solution-kicker solution-kicker--dark">LINHA TLC AGRO</span><h2>Controle eficiente de moscas com a linha <em>Ecomax</em>.</h2><p className="tlc-lead">Uma das soluções mais reconhecidas da TLC Agro para o controle sustentável de moscas no campo.</p><div className="use-tags">{["Granjas", "Currais", "Estábulos", "Haras", "Confinamentos", "Áreas externas"].map((tag) => <span key={tag}>{tag}</span>)}</div><ContactLink className="dark-button">Comprar ou pedir orientação <ArrowRight size={18} /></ContactLink></div><div className="tlc-products" data-reveal><div className="tlc-product tlc-product--bottle"><Image unoptimized src="/media/tlc/ecomax-produtos.png" alt="Atrativo orgânico Ecomax" width={620} height={494} /><span>Atrativo orgânico</span></div><div className="tlc-product tlc-product--trap"><Image unoptimized src="/media/tlc/ecomax-armadilha.png" alt="Armadilha para moscas Ecomax" width={1080} height={1080} /><span>Armadilha Ecomax</span></div></div></div><div className="container how-grid" data-reveal><header><small>COMO FUNCIONA</small><h3>Três etapas. Aplicação simples.</h3></header><ol><li><b>01</b><div><strong>Abasteça</strong><span>Coloque o atrativo orgânico dentro da armadilha.</span></div></li><li><b>02</b><div><strong>Posicione</strong><span>Instale em pontos estratégicos com incidência de moscas.</span></div></li><li><b>03</b><div><strong>Monitore</strong><span>As moscas ficam retidas; esvazie o reservatório periodicamente.</span></div></li></ol></div></section>

      <section id="resultados" className="section proof-section"><div className="container"><header className="proof-heading" data-reveal><div><div className="eyebrow"><span /> Campo, não promessa</div><h2>Aplicações e resultados que podem ser vistos.</h2></div><p>O espaço está preparado para receber os materiais originais da Susttenta, TLC Agro, Embio e clientes autorizados sem refazer o layout.</p></header><div className="proof-layout"><article className="proof-feature" data-reveal><video controls preload="none" poster="/media/campo-01.jpg"><source src="/media/campo-01.mp4" type="video/mp4" /></video><div><span>APLICAÇÃO EM LAGOA</span><h3>Tratamento acompanhado em campo</h3><p>Registro provisório. Será substituído pelo vídeo original aprovado.</p></div></article><div className="proof-side"><article className="proof-card" data-reveal><Image unoptimized src="/media/campo-02.jpg" alt="Lagoa em propriedade rural" fill sizes="(max-width: 900px) 100vw, 34vw" /><div><span>ANTES E DEPOIS</span><h3>Comparação visual do sistema</h3></div></article><article className="authority-card" data-reveal><BadgeCheck /><small>CONTEÚDO DE AUTORIDADE</small><h3>Primos Agro</h3><p>Bloco reservado para a publicação oficial da aplicação do Ecomax, após inserção do arquivo ou link autorizado.</p><span className="pending-label">Material oficial pendente</span></article></div></div></div></section>

      <section className="other-products"><div className="container"><header className="section-heading" data-reveal><div className="eyebrow"><span /> Outras soluções Embio</div><h2>Aplicações específicas, sem indicação genérica.</h2></header><div className="other-grid"><article data-reveal><div className="other-product__image"><Image unoptimized src="/media/embio-official/embio-5000.webp" alt="Produto Embio 5000+" width={900} height={900} /></div><div><small>CAMAS E CONFINAMENTOS</small><h3>Embio 5000+</h3><p>Voltado a ambientes de bovinos, ovinos e caprinos, com foco em ambiência, patógenos, larvas e moscas.</p><ContactLink className="text-button">Consultar solução <ArrowRight size={16} /></ContactLink></div></article><article data-reveal><div className="other-product__image"><Image unoptimized src="/media/embio-official/embio-8000.webp" alt="Produto Embio 8000" width={900} height={900} /></div><div><small>EFLUENTES INDUSTRIAIS</small><h3>Embio 8000</h3><p>Alternativa para efluentes industriais e agroindustriais com presença de óleos, gorduras e carga orgânica específica.</p><ContactLink className="text-button">Consultar solução <ArrowRight size={16} /></ContactLink></div></article></div></div></section>

      <section className="about-section"><div className="container about-grid"><div className="about-seal" data-reveal><Image unoptimized src="/favicon-master-1024.png" alt="Símbolo Susttenta" width={360} height={360} /><div><span>EMBIO</span><i /><span>TLC AGRO</span></div></div><div className="about-copy" data-reveal><div className="eyebrow"><span /> Sobre a Susttenta</div><h2>Representar marcas é só o começo. Nosso papel é orientar.</h2><p>A Susttenta reúne soluções complementares para desafios do campo e conduz cada atendimento de forma consultiva: entender a operação, selecionar a tecnologia e orientar a aplicação.</p><div className="about-points"><span><BadgeCheck /> Portfólio especializado</span><span><Gauge /> Diagnóstico do cenário</span><span><Sprout /> Orientação de aplicação</span><span><MessageCircle /> Atendimento próximo</span></div></div></div></section>

      <section className="section video-section"><div className="container"><header className="section-heading section-heading--center" data-reveal><div className="eyebrow"><span /> Biblioteca de campo</div><h2>Vídeos e aplicações reais</h2><p>Uma área viva para demonstrar manejo, instalação, resultados e depoimentos.</p></header><div className="video-grid"><article data-reveal><div className="video-poster"><Image unoptimized src="/media/depoimento-01.jpg" alt="Depoimento em propriedade rural" fill /><span><Play fill="currentColor" /></span></div><small>DEPOIMENTO</small><h3>Quem aplica conta o resultado</h3></article><article data-reveal><div className="video-poster"><Image unoptimized src="/media/campo-01.jpg" alt="Aplicação em lagoa" fill /><span><Play fill="currentColor" /></span></div><small>EMBIOFERT</small><h3>Aeração e tratamento em campo</h3></article><article data-reveal><div className="video-poster"><Image unoptimized src="/media/tlc/ecomax-campo.png" alt="Aplicação Ecomax no campo" fill /><span><Play fill="currentColor" /></span></div><small>ECOMAX</small><h3>Instalação da armadilha</h3></article></div><p className="media-note">Imagens e vídeos provisórios, organizados para substituição pelos arquivos finais aprovados.</p></div></section>

      <section className="faq-section"><div className="container faq-grid"><header data-reveal><div className="eyebrow"><span /> Perguntas frequentes</div><h2>Antes da escolha, vem a orientação.</h2><p>As respostas abaixo ajudam a diferenciar as linhas. A indicação final depende do seu sistema.</p><ContactLink className="text-button">Tenho outra dúvida <ArrowRight size={17} /></ContactLink></header><div className="faq-list" data-reveal>{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>

      <section id="contato" className="contact-section"><div className="contact-rings" /><div className="container contact-content" data-reveal><span>FALE COM A SUSTTENTA</span><h2>Seu problema não precisa de um produto qualquer. Precisa da solução certa.</h2><p>Conte como funciona a sua operação. Nossa equipe ajuda a avaliar o cenário e indicar o próximo passo.</p><ContactLink className="primary-button primary-button--yellow"><MessageCircle size={20} /> Iniciar atendimento <ArrowRight size={18} /></ContactLink><small>Atendimento comercial e orientação técnica</small></div></section>
    </main>

    <footer className="site-footer"><div className="footer-accent" /><div className="container footer-grid"><div className="footer-brand"><div className="footer-brand__lockup"><Image unoptimized src="/favicon-master-1024.png" alt="" width={62} height={62} /><Image unoptimized src="/logo-susttenta-wordmark.png" alt="Susttenta" width={180} height={27} /></div><p>Soluções biotecnológicas para granjas, propriedades rurais, lagoas, biodigestores e controle de moscas.</p></div><div><strong>Soluções</strong><a href="#embiofert">Tratamento Embiofert</a><a href="#linha-embio">Linha Embio</a><a href="#tlc-agro">TLC Agro · Ecomax</a><a href="#resultados">Resultados</a></div><div><strong>Legal</strong><Link href="/privacidade">Privacidade e LGPD</Link><Link href="/cookies">Política de Cookies</Link><Link href="/termos">Termos de Uso</Link><button onClick={() => window.dispatchEvent(new Event("open-cookie-settings"))}>Gerenciar cookies</button></div></div><div className="container footer-bottom"><span>© 2026 Susttenta. Todos os direitos reservados.</span><span>Embio e TLC Agro são marcas representadas pela Susttenta.</span></div></footer>
    <ContactLink className="floating-contact" ariaLabel="Ir para o atendimento"><MessageCircle size={28} /></ContactLink>
    <CookieConsent />
  </>;
}
