import Image from "next/image";
import { ArrowRight, Droplets, ShieldAlert, Wind } from "lucide-react";
import { ProductVideoGallery } from "./product-video-gallery";
import { productVideos } from "./site-data";
import { WhatsAppLink } from "./site-chrome";
import { whatsappMessages } from "./whatsapp";

export function Embio3100Section() {
  const videos = productVideos.filter((item) => item.product === "embio-3100");
  return <section id="embio-3100" className="section embio-product-section embio-3100-section"><div className="container"><div className="product-feature"><div className="product-stage" data-reveal><span>Ambiência interna</span><Image src="/media/embio-official/embio-3100.webp" alt="Embalagem oficial do Embio 3100" width={700} height={700} sizes="(max-width: 850px) 82vw, 38vw" /></div><div data-reveal><p className="section-label">Instalações de suínos</p><h2>Embio 3100</h2><p className="lead">Aplicação orientada para apoiar a ambiência e o manejo interno das instalações.</p><ul className="technical-list"><li><Wind />Auxílio no controle de gases e odores.</li><li><Droplets />Apoio no manejo do cascão e na rotina de limpeza.</li><li><ShieldAlert />Atuação sobre condições relacionadas a larvas e moscas.</li></ul><aside className="biodigester-warning"><strong>Atenção ao destino dos dejetos.</strong> O Embio 3100 não é a principal indicação para instalações cujo dejeto segue diretamente para biodigestor. Nesses sistemas, a recomendação deve considerar o Embio 6000 e passar por avaliação técnica.</aside><WhatsAppLink message={whatsappMessages.embio3100} ariaLabel="Consultar aplicação do Embio 3100 pelo WhatsApp" className="button button-primary whatsapp-pulse">Consultar aplicação do Embio 3100<ArrowRight size={18} /></WhatsAppLink></div></div><div className="video-block-heading"><p className="section-label">Galeria preparada</p><h3>Aplicação, ambiência e demonstração técnica</h3></div><ProductVideoGallery items={videos} /></div></section>;
}

export function Embio6000Section() {
  const videos = productVideos.filter((item) => item.product === "embio-6000");
  return <section id="embio-6000" className="section embio-product-section embio-6000-section"><div className="container"><div className="product-feature is-reversed"><div className="product-stage" data-reveal><span>Fluxo com biodigestor</span><Image src="/media/embio-official/embio-6000.webp" alt="Embalagem oficial do Embio 6000" width={600} height={1040} sizes="(max-width: 850px) 60vw, 28vw" /></div><div data-reveal><p className="section-label">Ambiência com preservação da matéria orgânica</p><h2>Embio 6000</h2><p className="lead">Indicado para instalações que enviam os dejetos ao biodigestor e precisam trabalhar a ambiência sem antecipar a degradação da matéria orgânica destinada ao biogás.</p><p>Pode auxiliar no manejo de gases, odores e condições relacionadas a larvas e moscas. Sua indicação é diferente da do Embio 3100 porque considera a destinação posterior dos dejetos ao processo anaeróbio.</p><aside><strong>Avaliação obrigatória.</strong> O produto não representa garantia de aumento de biogás. Estrutura, fluxo e rotina operacional precisam ser compreendidos antes da aplicação.</aside><WhatsAppLink message={whatsappMessages.embio6000} ariaLabel="Consultar aplicação do Embio 6000 pelo WhatsApp" className="button button-yellow whatsapp-pulse">Consultar aplicação do Embio 6000<ArrowRight size={18} /></WhatsAppLink></div></div><div className="video-block-heading"><p className="section-label">Conteúdo futuro</p><h3>Demonstração, aplicação e explicação técnica</h3></div><ProductVideoGallery items={videos} /></div></section>;
}

export function OtherEmbioSolutions() {
  return <section id="outras-solucoes" className="section other-embio"><div className="container"><header className="section-heading" data-reveal><p className="section-label">Portfólio complementar Embio</p><h2>Outras soluções para cenários específicos</h2><p>Embio 5000+ e Embio 8000 ampliam o atendimento a camas, confinamentos e efluentes. O diagnóstico define se a aplicação é compatível com a operação.</p></header><div className="other-products-grid"><article data-reveal><div className="other-product-image"><Image src="/media/embio-official/embio-5000.webp" alt="Embalagem oficial do Embio 5000+" fill sizes="(max-width: 760px) 88vw, 36vw" /></div><div><span>Camas e confinamentos</span><h3>Embio 5000+</h3><p>Aplicação em camas e confinamentos de bovinos, ovinos e caprinos, com foco em ambiência e manejo dos resíduos conforme as condições da estrutura.</p><WhatsAppLink message={whatsappMessages.embio5000} ariaLabel="Consultar aplicação do Embio 5000+ pelo WhatsApp">Consultar Embio 5000+<ArrowRight size={17} /></WhatsAppLink></div></article><article data-reveal><div className="other-product-image"><Image src="/media/embio-official/embio-8000.webp" alt="Embalagem oficial do Embio 8000" fill sizes="(max-width: 760px) 88vw, 36vw" /></div><div><span>Efluentes agroindustriais</span><h3>Embio 8000</h3><p>Direcionado a efluentes industriais e agroindustriais, inclusive cenários com presença de óleos e gorduras. A recomendação depende do diagnóstico do efluente e do sistema.</p><WhatsAppLink message={whatsappMessages.embio8000} ariaLabel="Consultar aplicação do Embio 8000 pelo WhatsApp">Consultar Embio 8000<ArrowRight size={17} /></WhatsAppLink></div></article></div></div></section>;
}
