import Image from "next/image";
import { ArrowRight, Droplets, ShieldAlert, Wind } from "lucide-react";
import { ProductVideoGallery } from "./product-video-gallery";
import { productVideos, type ProductVideo } from "./site-data";
import { WhatsAppLink } from "./site-chrome";
import { whatsappMessages } from "./whatsapp";

export function Embio3100Section({ onOpen }: { onOpen: (item: ProductVideo) => void }) {
  const videos = productVideos.filter((item) => item.product === "embio-3100");
  return <section id="embio-3100" className="section embio-product-section embio-3100-section"><div className="container"><div className="product-feature"><div className="product-stage product-stage-evidence" data-reveal><span>Registro de ambiência</span><Image src="/media/embio-2026/images/embio-3100-comparativo-ambiencia.webp" alt="Registro comparativo de medições de amônia e dióxido de carbono apresentado para o Embio 3100" width={1200} height={480} sizes="(max-width: 850px) 92vw, 42vw" /><small>Material comparativo fornecido pela Embio. A resposta varia conforme instalação, manejo e condições de medição.</small></div><div data-reveal><p className="section-label">Instalações de suínos</p><h2>Embio 3100</h2><p className="lead">Aplicação orientada para apoiar a ambiência e o manejo interno das instalações.</p><ul className="technical-list"><li><Wind />Auxílio no controle de gases e odores.</li><li><Droplets />Apoio no manejo do cascão e na rotina de limpeza.</li><li><ShieldAlert />Atuação sobre condições relacionadas a larvas e moscas.</li></ul><aside className="biodigester-warning"><strong>Atenção ao destino dos dejetos.</strong> O Embio 3100 não é a principal indicação para instalações cujo dejeto segue diretamente para biodigestor. Nesses sistemas, a recomendação deve considerar o Embio 6000 e passar por avaliação técnica.</aside><WhatsAppLink message={whatsappMessages.embio3100} ariaLabel="Consultar aplicação do Embio 3100 pelo WhatsApp" className="button button-primary whatsapp-pulse">Consultar aplicação do Embio 3100<ArrowRight size={18} /></WhatsAppLink></div></div><div className="video-block-heading"><p className="section-label">Experiência de campo</p><h3>O produtor fala sobre a ambiência no barracão</h3><p>Relato apresentado pela Embio; a recomendação depende da avaliação técnica de cada instalação.</p></div><ProductVideoGallery items={videos} onOpen={onOpen} compact /></div></section>;
}

export function Embio6000Section({ onOpen }: { onOpen: (item: ProductVideo) => void }) {
  const videos = productVideos.filter((item) => item.product === "embio-6000");
  return <section id="embio-6000" className="section embio-product-section embio-6000-section"><div className="container"><div className="product-feature is-reversed"><div className="product-stage product-stage-presentation" data-reveal><span>Fluxo com biodigestor</span><Image src="/media/embio-2026/images/embio-6000-biodigestao.webp" alt="Apresentação oficial do Embio 6000 para sistemas ligados à biodigestão" width={1600} height={900} sizes="(max-width: 850px) 92vw, 44vw" /></div><div data-reveal><p className="section-label">Ambiência com preservação da matéria orgânica</p><h2>Embio 6000</h2><p className="lead">Indicado para instalações que enviam os dejetos ao biodigestor e precisam trabalhar a ambiência sem antecipar a degradação da matéria orgânica destinada ao biogás.</p><p>Pode auxiliar no manejo de gases, odores e condições relacionadas a larvas e moscas. Sua indicação é diferente da do Embio 3100 porque considera a destinação posterior dos dejetos ao processo anaeróbio.</p><aside><strong>Avaliação obrigatória.</strong> O produto não representa garantia de aumento de biogás. Estrutura, fluxo e rotina operacional precisam ser compreendidos antes da aplicação.</aside><WhatsAppLink message={whatsappMessages.embio6000} ariaLabel="Consultar aplicação do Embio 6000 pelo WhatsApp" className="button button-yellow whatsapp-pulse">Consultar aplicação do Embio 6000<ArrowRight size={18} /></WhatsAppLink></div></div><div className="video-block-heading"><p className="section-label">Experiências de campo</p><h3>Relatos em operações conectadas à biodigestão</h3><p>Conteúdos fornecidos pela Embio. Os relatos são experiências individuais e não representam garantia de desempenho.</p></div><ProductVideoGallery items={videos} onOpen={onOpen} /></div></section>;
}

export function OtherEmbioSolutions() {
  return <section id="outras-solucoes" className="section other-embio"><div className="container"><header className="section-heading" data-reveal><p className="section-label">Portfólio complementar Embio</p><h2>Soluções específicas, indicadas com critério</h2><p>Embio 5000+ e Embio 8000 ampliam o atendimento a camas, confinamentos e efluentes. O diagnóstico define se a aplicação é compatível com a operação.</p></header><div className="other-products-grid"><article data-reveal><div className="other-product-type" aria-hidden="true"><span>EMBIO</span><strong>5000+</strong><small>Camas e confinamentos</small></div><div><span>Camas e confinamentos</span><h3>Embio 5000+</h3><p>Aplicação em camas e confinamentos de bovinos, ovinos e caprinos, com foco em ambiência e manejo dos resíduos conforme as condições da estrutura.</p><WhatsAppLink message={whatsappMessages.embio5000} ariaLabel="Consultar aplicação do Embio 5000+ pelo WhatsApp">Consultar Embio 5000+<ArrowRight size={17} /></WhatsAppLink></div></article><article data-reveal><div className="other-product-image other-product-image-new"><Image src="/media/embio-2026/images/embio-8000-produto.webp" alt="Embalagem do Embio 8000 fornecida pela Embio" fill sizes="(max-width: 760px) 88vw, 36vw" /></div><div><span>Efluentes agroindustriais</span><h3>Embio 8000</h3><p>Direcionado a efluentes industriais e agroindustriais, inclusive cenários com presença de óleos e gorduras. A recomendação depende do diagnóstico do efluente e do sistema.</p><WhatsAppLink message={whatsappMessages.embio8000} ariaLabel="Consultar aplicação do Embio 8000 pelo WhatsApp">Consultar Embio 8000<ArrowRight size={17} /></WhatsAppLink></div></article></div></div></section>;
}
