export const navigationItems = [
  { label: "Início", href: "#inicio" }, { label: "Embiofert", href: "#embiofert" }, { label: "Embio 3100", href: "#embio-3100" }, { label: "Embio 6000", href: "#embio-6000" }, { label: "Embio 8000", href: "#embio-8000" }, { label: "TLC Agro", href: "#tlc-agro" }, { label: "Sobre Pedro", href: "#pedro" }, { label: "Contato", href: "#contato" },
] as const;

export type ProductVideo = { id: string; title: string; description: string; eyebrow: string; product: "embio" | "embiofert" | "embio-3100" | "embio-6000" | "tlc"; status: "available" | "coming-soon"; videoSrc: string | null; posterSrc: string; aspectRatio?: string };

// aspectRatio: proporção real do arquivo (largura da imagem/vídeo original medida com ffprobe),
// usada pelo componente de reprodução inline para não impor uma altura rígida.
// Embio: 1280x720 (16 / 9). TLC/EcoMax: 720x1280 (9 / 16).

export const productVideos: ProductVideo[] = [
  { id: "embio-tecnologia", product: "embio", status: "available", eyebrow: "Estrutura Embio", title: "Tecnologia, laboratório e presença no campo", description: "Uma visão da estrutura que conecta desenvolvimento, fabricação, conhecimento técnico e acompanhamento da aplicação.", videoSrc: "/media/embio-2026/videos/embio-tecnologia-e-laboratorio.mp4", posterSrc: "/media/embio-2026/posters/embio-tecnologia-e-laboratorio.webp", aspectRatio: "16 / 9" },
  { id: "embiofert-operacao", product: "embiofert", status: "available", eyebrow: "Operação real", title: "Propulsor Embio em funcionamento", description: "Registro do equipamento promovendo movimentação e aeração em uma lagoa de dejetos.", videoSrc: "/media/embio-2026/videos/embiofert-propulsor-em-operacao.mp4", posterSrc: "/media/embio-2026/posters/embiofert-propulsor-em-operacao.webp", aspectRatio: "16 / 9" },
  { id: "embiofert-relato-campo", product: "embiofert", status: "available", eyebrow: "Relato de campo", title: "Experiência com o Tratamento Embiofert", description: "Relato fornecido pela Embio sobre a rotina observada em uma operação com lagoa tratada.", videoSrc: "/media/embio-2026/videos/embiofert-relato-de-campo.mp4", posterSrc: "/media/embio-2026/posters/embiofert-relato-de-campo.webp", aspectRatio: "16 / 9" },
  { id: "embiofert-aproveitamento", product: "embiofert", status: "available", eyebrow: "Relato de campo", title: "Manejo e aproveitamento agronômico", description: "Experiência apresentada sobre o manejo do dejeto tratado e seu uso como fonte de nutrientes no solo.", videoSrc: "/media/embio-2026/videos/embiofert-aproveitamento-agronomico.mp4", posterSrc: "/media/embio-2026/posters/embiofert-aproveitamento-agronomico.webp", aspectRatio: "16 / 9" },
  { id: "3100-relato-ambiencia", product: "embio-3100", status: "available", eyebrow: "Relato de produtor", title: "Ambiência no barracão", description: "Relato fornecido pela Embio sobre a percepção do produtor após a adoção do Embio 3100 na instalação.", videoSrc: "/media/embio-2026/videos/embio-3100-relato-ambiencia.mp4", posterSrc: "/media/embio-2026/posters/embio-3100-relato-ambiencia.webp", aspectRatio: "16 / 9" },
  { id: "6000-relato-biodigestor", product: "embio-6000", status: "available", eyebrow: "Relato de campo", title: "Operação conectada ao biodigestor", description: "Experiência apresentada em uma propriedade que utiliza o Embio 6000 no fluxo anterior à biodigestão.", videoSrc: "/media/embio-2026/videos/embio-6000-relato-biodigestor.mp4", posterSrc: "/media/embio-2026/posters/embio-6000-relato-biodigestor.webp", aspectRatio: "16 / 9" },
  { id: "6000-relato-ambiencia", product: "embio-6000", status: "available", eyebrow: "Relato de produtor", title: "Ambiência e manejo na instalação", description: "Relato fornecido pela Embio sobre a experiência de campo com o produto em uma operação ligada à biodigestão.", videoSrc: "/media/embio-2026/videos/embio-6000-relato-ambiencia.mp4", posterSrc: "/media/embio-2026/posters/embio-6000-relato-ambiencia.webp", aspectRatio: "16 / 9" },
  { id: "ecomax-demonstracao", product: "tlc", status: "available", eyebrow: "Demonstração oficial", title: "Como o conjunto Ecomax é utilizado", description: "Demonstração publicada pela TLC Agro e carregada somente após sua interação.", videoSrc: "/media/tlc-official/videos/ecomax-como-funciona.mp4", posterSrc: "/media/tlc-official/thumbnails/ecomax-como-funciona.webp", aspectRatio: "9 / 16" },
  { id: "tlc-relato-01", product: "tlc", status: "available", eyebrow: "Relato publicado pela TLC Agro", title: "Experiência apresentada pela fabricante", description: "Sem identificação pública suficiente para atribuir nome, propriedade ou vínculo com a Susttenta.", videoSrc: "/media/tlc-official/videos/tlc-relato-01.mp4", posterSrc: "/media/tlc-official/thumbnails/tlc-relato-01.webp", aspectRatio: "9 / 16" },
  { id: "tlc-relato-02", product: "tlc", status: "available", eyebrow: "Relato publicado pela TLC Agro", title: "Registro compartilhado pela TLC Agro", description: "Apresentado no contexto original, sem resultado atribuído ou identificação não confirmada.", videoSrc: "/media/tlc-official/videos/tlc-relato-02.mp4", posterSrc: "/media/tlc-official/thumbnails/tlc-relato-02.webp", aspectRatio: "9 / 16" },
];

export const faqItems = [
  { question: "O que é o Tratamento Embiofert?", answer: "É um tratamento integrado para lagoas e sistemas com dejetos bovinos e suínos que combina Embio 3000, Propulsor Embio, aeração, movimentação e atuação biológica. A implantação depende da avaliação do volume, da carga orgânica e da estrutura existente." },
  { question: "Como Embio 3000 e Propulsor trabalham juntos?", answer: "O Propulsor promove circulação, aeração e homogeneização, enquanto o Embio 3000 fornece o componente biológico. A movimentação favorece a distribuição dos microrganismos e o contato com a matéria orgânica." },
  { question: "Qual a diferença entre Embio 3100 e Embio 6000?", answer: "O Embio 3100 é direcionado ao manejo interno de instalações de suínos sem envio direto ao biodigestor. O Embio 6000 atende instalações que enviam dejetos ao biodigestor, preservando a matéria orgânica destinada ao processo anaeróbio." },
  { question: "Qual solução considerar quando existe biodigestor?", answer: "O Embio 6000 deve ser considerado nesse cenário, mas a recomendação final depende do fluxo dos dejetos, das estruturas intermediárias e das condições da operação." },
  { question: "Para que serve o Embio 8000?", answer: "O Embio 8000 é direcionado ao tratamento biotecnológico de efluentes industriais e agroindustriais com alta concentração de óleos e ácidos graxos. A recomendação depende da caracterização do efluente, da carga orgânica e das condições da estação de tratamento." },
  { question: "Como funciona a linha Ecomax?", answer: "O atrativo e a armadilha formam um conjunto de atração, entrada e retenção de moscas. Posicionamento, monitoramento, limpeza e manejo ambiental influenciam a utilização." },
  { question: "A Susttenta realiza avaliação antes da recomendação?", answer: "Sim. O atendimento considera ambiente, estrutura, manejo, destino dos dejetos e objetivo da operação antes de direcionar uma solução." },
  { question: "Como falar diretamente com Pedro?", answer: "Use o botão de WhatsApp desta página. Se possível, informe o tipo de operação, o desafio observado e como os resíduos ou dejetos são manejados." },
] as const;
