export const navigationItems = [
  { label: "Início", href: "#inicio" }, { label: "Embiofert", href: "#embiofert" }, { label: "Embio 3100", href: "#embio-3100" }, { label: "Embio 6000", href: "#embio-6000" }, { label: "Outras soluções", href: "#outras-solucoes" }, { label: "TLC Agro", href: "#tlc-agro" }, { label: "Sobre Pedro", href: "#pedro" }, { label: "Contato", href: "#contato" },
] as const;

export type ProductVideo = { id: string; title: string; description: string; eyebrow: string; product: "embiofert" | "embio-3100" | "embio-6000" | "tlc"; status: "available" | "coming-soon"; videoSrc: string | null; posterSrc: string };

export const productVideos: ProductVideo[] = [
  { id: "embiofert-demonstracao", product: "embiofert", status: "coming-soon", eyebrow: "Conteúdo em preparação", title: "Demonstração do Tratamento Embiofert", description: "Espaço preparado para receber um vídeo horizontal oficial de aplicação do Embio 3000 com o Propulsor.", videoSrc: null, posterSrc: "/media/embio-official/embiofert.webp" },
  { id: "3100-aplicacao", product: "embio-3100", status: "coming-soon", eyebrow: "Aplicação em granja", title: "Aplicação em granja", description: "Área reservada para uma demonstração oficial da aplicação orientada em instalações de suínos.", videoSrc: null, posterSrc: "/media/embio-official/embio-3100.webp" },
  { id: "3100-ambiencia", product: "embio-3100", status: "coming-soon", eyebrow: "Ambiência e manejo", title: "Ambiência e manejo interno", description: "Área preparada para conteúdo oficial sobre manejo interno, gases, odores e rotina de limpeza.", videoSrc: null, posterSrc: "/media/embio-official/embio-3100.webp" },
  { id: "3100-demonstracao", product: "embio-3100", status: "coming-soon", eyebrow: "Demonstração técnica", title: "Resultado ou demonstração técnica", description: "O conteúdo será incluído somente quando houver material verificável e autorizado.", videoSrc: null, posterSrc: "/media/embio-official/embio-3100.webp" },
  { id: "6000-demonstracao", product: "embio-6000", status: "coming-soon", eyebrow: "Demonstração", title: "Demonstração do Embio 6000", description: "Espaço preparado para demonstração oficial em instalações ligadas a biodigestores.", videoSrc: null, posterSrc: "/media/embio-official/embio-6000.webp" },
  { id: "6000-aplicacao", product: "embio-6000", status: "coming-soon", eyebrow: "Aplicação", title: "Aplicação orientada", description: "Área reservada para uma aplicação oficial, sem antecipar dosagens ou protocolos.", videoSrc: null, posterSrc: "/media/embio-official/embio-6000.webp" },
  { id: "6000-explicacao", product: "embio-6000", status: "coming-soon", eyebrow: "Explicação técnica", title: "Integração com o biodigestor", description: "O futuro conteúdo explicará a diferença de indicação sem prometer aumento de biogás.", videoSrc: null, posterSrc: "/media/embio-official/embio-6000.webp" },
  { id: "ecomax-demonstracao", product: "tlc", status: "available", eyebrow: "Demonstração oficial", title: "Como o conjunto Ecomax é utilizado", description: "Demonstração publicada pela TLC Agro e carregada somente após sua interação.", videoSrc: "/media/tlc-official/videos/ecomax-como-funciona.mp4", posterSrc: "/media/tlc-official/thumbnails/ecomax-como-funciona.webp" },
  { id: "tlc-relato-01", product: "tlc", status: "available", eyebrow: "Relato publicado pela TLC Agro", title: "Experiência apresentada pela fabricante", description: "Sem identificação pública suficiente para atribuir nome, propriedade ou vínculo com a Susttenta.", videoSrc: "/media/tlc-official/videos/tlc-relato-01.mp4", posterSrc: "/media/tlc-official/thumbnails/tlc-relato-01.webp" },
  { id: "tlc-relato-02", product: "tlc", status: "available", eyebrow: "Relato publicado pela TLC Agro", title: "Registro compartilhado pela TLC Agro", description: "Apresentado no contexto original, sem resultado atribuído ou identificação não confirmada.", videoSrc: "/media/tlc-official/videos/tlc-relato-02.mp4", posterSrc: "/media/tlc-official/thumbnails/tlc-relato-02.webp" },
];

export const faqItems = [
  { question: "O que é o Tratamento Embiofert?", answer: "É um tratamento integrado para lagoas e sistemas com dejetos bovinos e suínos que combina Embio 3000, Propulsor Embio, aeração, movimentação e atuação biológica. A implantação depende da avaliação do volume, da carga orgânica e da estrutura existente." },
  { question: "Como Embio 3000 e Propulsor trabalham juntos?", answer: "O Propulsor promove circulação, aeração e homogeneização, enquanto o Embio 3000 fornece o componente biológico. A movimentação favorece a distribuição dos microrganismos e o contato com a matéria orgânica." },
  { question: "Qual a diferença entre Embio 3100 e Embio 6000?", answer: "O Embio 3100 é direcionado ao manejo interno de instalações de suínos sem envio direto ao biodigestor. O Embio 6000 atende instalações que enviam dejetos ao biodigestor, preservando a matéria orgânica destinada ao processo anaeróbio." },
  { question: "Qual solução considerar quando existe biodigestor?", answer: "O Embio 6000 deve ser considerado nesse cenário, mas a recomendação final depende do fluxo dos dejetos, das estruturas intermediárias e das condições da operação." },
  { question: "Para que servem Embio 5000+ e Embio 8000?", answer: "O Embio 5000+ atende aplicações em camas e confinamentos de bovinos, ovinos e caprinos. O Embio 8000 é destinado a efluentes industriais e agroindustriais, inclusive cenários com óleos e gorduras. Ambos exigem diagnóstico." },
  { question: "Como funciona a linha Ecomax?", answer: "O atrativo e a armadilha formam um conjunto de atração, entrada e retenção de moscas. Posicionamento, monitoramento, limpeza e manejo ambiental influenciam a utilização." },
  { question: "A Susttenta realiza avaliação antes da recomendação?", answer: "Sim. O atendimento considera ambiente, estrutura, manejo, destino dos dejetos e objetivo da operação antes de direcionar uma solução." },
  { question: "Como falar diretamente com Pedro?", answer: "Use o botão de WhatsApp desta página. Se possível, informe o tipo de operação, o desafio observado e como os resíduos ou dejetos são manejados." },
] as const;
