import Image from "next/image";
import { ArrowRight, Blend, Check, CircleDot, Gauge, Layers3, Wind } from "lucide-react";
import { technicalChallenges } from "./site-data";
import { WhatsAppLink } from "./site-chrome";
import { whatsappMessages } from "./whatsapp";

const icons = { layers: Layers3, wind: Wind, target: CircleDot, blend: Blend, gauge: Gauge };

export function TechnicalChallenges() {
  return <section id="desafios" className="section challenges-section"><div className="container"><header className="section-heading" data-reveal><p className="section-label">Diagnóstico antes da indicação</p><h2>Desafios que comprometem a eficiência da operação</h2><p>Acúmulo de matéria orgânica, baixa homogeneização, emissão de gases, odores e proliferação de moscas exigem diagnóstico correto e aplicação compatível com cada sistema produtivo.</p></header><div className="challenges-grid">{technicalChallenges.map((item) => { const Icon = icons[item.icon]; return <article key={item.title} data-reveal><Icon /><h3>{item.title}</h3><p>{item.text}</p></article>; })}</div></div></section>;
}

export function EmbiofertSection() {
  const stages = ["Aeração", "Homogeneização", "Distribuição biológica", "Degradação da matéria orgânica"];
  return <section id="embiofert" className="embiofert-section"><div className="container embiofert-grid">
    <div className="embiofert-media" data-reveal><div className="embiofert-rings" aria-hidden="true" /><Image src="/media/embio-official/embiofert.webp" alt="Conjunto oficial Embio 3000 e Propulsor Embio" width={900} height={900} sizes="(max-width: 900px) 92vw, 44vw" /><span>Imagem oficial Embio</span></div>
    <div className="embiofert-copy" data-reveal><p className="section-label">Tratamento Embiofert</p><h2>Atuação biológica, aeração e movimento em um sistema integrado</h2><p>O Tratamento Embiofert combina o bioestimulador Embio 3000 ao Propulsor Embio para apoiar o manejo de lagoas com dejetos bovinos e suínos. Enquanto o equipamento promove circulação e incorporação de oxigênio, o componente biológico atua sobre a matéria orgânica em condições mais favoráveis.</p><p>A homogeneização ajuda a distribuir sólidos e microrganismos pelo volume tratado. O processo pode contribuir para reduzir sedimentos, odores e condições favoráveis à proliferação de moscas, além de facilitar o manejo operacional. O dimensionamento depende do volume, da carga orgânica, da estrutura e da rotina de cada propriedade.</p><WhatsAppLink message={whatsappMessages.embiofert} ariaLabel="Solicitar orientação sobre o Tratamento Embiofert pelo WhatsApp" className="button button-yellow">Receber orientação sobre Embiofert<ArrowRight size={18} /></WhatsAppLink></div>
  </div><div className="container process-line" data-reveal>{stages.map((stage, index) => <div key={stage}><span>{index + 1}</span><div><Check size={17} /><strong>{stage}</strong></div></div>)}</div><div className="container technical-note"><strong>Avaliação técnica antes da implantação</strong><p>Aplicação, dosagem e configuração do Propulsor devem ser definidas após a leitura do sistema. O infográfico representa a sequência operacional e não substitui projeto ou protocolo técnico.</p></div></section>;
}

export function EmbioProducts() {
  return <section id="linha-embio" className="section embio-products"><div className="container"><header className="section-heading" data-reveal><p className="section-label">Ambiência em instalações de suínos</p><h2>Embio 3100 e Embio 6000 atendem destinos diferentes para os dejetos</h2><p>A indicação correta considera o fluxo da instalação e, principalmente, se a matéria orgânica seguirá para geração de biogás.</p></header>
    <div className="embio-product-grid"><article data-reveal><div className="product-image"><Image src="/media/embio-official/embio-3100.webp" alt="Embalagem oficial do Embio 3100" width={700} height={700} /></div><div><span>Instalação interna sem destino direto ao biodigestor</span><h3>Embio 3100</h3><p>Destinado à ambiência interna em instalações de suínos. Pode auxiliar no manejo de gases, odores, condições relacionadas a larvas e moscas, cascão e rotina de limpeza.</p><aside><strong>Atenção ao biodigestor</strong>Não é a recomendação principal quando o dejeto segue diretamente para o biodigestor.</aside><WhatsAppLink message={whatsappMessages.embio3100} ariaLabel="Saber mais sobre a aplicação do Embio 3100 pelo WhatsApp">Consultar Embio 3100<ArrowRight size={17} /></WhatsAppLink></div></article>
      <article data-reveal><div className="product-image"><Image src="/media/embio-official/embio-6000.webp" alt="Embalagem oficial do Embio 6000" width={600} height={1040} /></div><div><span>Instalação com envio de dejetos ao biodigestor</span><h3>Embio 6000</h3><p>Desenvolvido para trabalhar a ambiência, gases, odores e condições ligadas a larvas e moscas preservando a matéria orgânica destinada à produção de biogás.</p><aside><strong>Indicação específica</strong>Sua formulação atende um fluxo operacional diferente do Embio 3100 e exige avaliação do sistema.</aside><WhatsAppLink message={whatsappMessages.embio6000} ariaLabel="Saber mais sobre o Embio 6000 para propriedades com biodigestor pelo WhatsApp">Consultar Embio 6000<ArrowRight size={17} /></WhatsAppLink></div></article></div>
    <div className="comparison-wrap" data-reveal><table aria-label="Comparação técnica entre Embio 3100 e Embio 6000"><thead><tr><th>Critério</th><th>Embio 3100</th><th>Embio 6000</th></tr></thead><tbody><tr><th>Aplicação principal</th><td>Instalação interna sem destino direto ao biodigestor</td><td>Instalação com envio de dejetos ao biodigestor</td></tr><tr><th>Objetivo</th><td>Ambiência e manejo interno</td><td>Ambiência com preservação da matéria orgânica para biogás</td></tr><tr><th>Avaliação técnica</th><td>Obrigatória</td><td>Obrigatória</td></tr></tbody></table></div>
  </div></section>;
}
