import Image from "next/image";
import { ArrowRight, LogIn, Magnet, ShieldCheck } from "lucide-react";
import { ProductVideoGallery } from "./product-video-gallery";
import { productVideos, type ProductVideo } from "./site-data";
import { WhatsAppLink } from "./site-chrome";
import { whatsappMessages } from "./whatsapp";

export function TlcEcomaxSection({ onOpen }: { onOpen: (item: ProductVideo) => void }) {
  const tlcVideos = productVideos.filter((item) => item.product === "tlc");
  return <section id="tlc-agro" className="tlc-section"><div className="brand-transition" aria-hidden="true"><span>Uma linha complementar, uma apresentação independente</span></div><div className="container tlc-intro"><div data-reveal><Image className="tlc-section-logo" src="/media/tlc-official/images/tlc-logo-original.svg" alt="TLC Agro" width={170} height={70} /><p className="section-label">Linha complementar representada pela Susttenta</p><h2>TLC Agro e a linha Ecomax</h2><p className="lead">Controle estratégico de moscas para ambientes rurais</p><p>O Ecomax combina atrativo e armadilha em uma estratégia de atração, entrada e retenção. Posicionamento, montagem, monitoramento e manejo adequados são essenciais; a solução não elimina a necessidade de higiene e controle ambiental.</p><div className="use-list">{["Granjas", "Currais", "Estábulos", "Haras", "Confinamentos", "Áreas externas"].map((place) => <span key={place}>{place}</span>)}</div><WhatsAppLink message={whatsappMessages.ecomax} ariaLabel="Conhecer a linha Ecomax pelo WhatsApp" className="button button-dark whatsapp-pulse">Conhecer a linha Ecomax<ArrowRight size={18} /></WhatsAppLink></div><div className="tlc-product-stage" data-reveal><div className="tlc-bottle"><Image src="/media/tlc-official/images/ecomax-produtos.webp" alt="Atrativo Ecomax em embalagem oficial" width={620} height={494} /></div><div className="tlc-trap"><Image src="/media/tlc-official/images/ecomax-armadilha-oficial.webp" alt="Armadilha Ecomax em demonstração oficial" fill sizes="(max-width: 900px) 62vw, 24vw" /></div><span>Materiais publicados no domínio oficial da TLC Agro</span></div></div>
    <div className="container capture-story" data-reveal><div><Magnet /><span>01</span><h3>Atração</h3><p>O conjunto cria um ponto de interesse para as moscas no ambiente monitorado.</p></div><div><LogIn /><span>02</span><h3>Entrada</h3><p>A geometria da armadilha permite a entrada das moscas atraídas.</p></div><div><ShieldCheck /><span>03</span><h3>Retenção</h3><p>O reservatório retém as moscas e precisa de acompanhamento e manejo.</p></div></div>
    <div className="container tlc-media-section"><header className="video-block-heading" data-reveal><p className="section-label">Materiais oficiais TLC Agro</p><h3>Demonstração e relatos publicados pela fabricante</h3><p>Os participantes não são apresentados como clientes da Susttenta e não recebem identificação ou resultados que não estejam confirmados na fonte.</p></header><ProductVideoGallery items={tlcVideos} onOpen={onOpen} /></div>
  </section>;
}
